set-option -sa terminal-overrides ",xterm:Tc"
set -g mouse on

unbind C-b
set -g prefix C-space
bind C-space send-prefix

bind -n M-H previous-window
bind -n M-L next-window

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @catppuccin_flavor 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tumx-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
